# pages-collection
# a Jekyll Digital Collection Generator
# designed for GH-Pages

# Site settings

# title of site appears in banner
title: digital practice collection
# tagline appears in banner
tagline: practicing building a collection
# This is the first practice collection I made based on work done by all members of the symposium
# this description might appear in search result lists, keep around 160 characters max
description: "A more complete description that will appear in meta tags and on the index page as a teaser."
# keywords appear in meta tags
keywords: "university of idaho, digital collections, digital humanities"
# creator of the digital collection, to appear in meta tags
author: sunfire60
# creator contact email for meta tags
email: sunray@wsu.edu
# collection project date, when did you publish this
collection-date: May 2018

# url is your gh-pages base, username.github.io
url: sunfire60.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /Digital-practice-collection
# repository is the github repository's full url
repository: https://github.com/sunfire60/Digital-practice-collection

# google services [optional!]
# leave these blank or comment out to NOT include google code
# google-tracking-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# build settings
permalink: pretty

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
